[package]
name = "rbfi"
version = "1.2.1"
edition = "2021"
description = "Extendable brainfuck interpreter written in Rust"
license = "BSD-3-Clause"
keywords = ["extendable","brainfuck","interpreter","wasm","cli"]
categories = ["command-line-utilities"]

[dependencies]
clap = {version = "4.3.19", features = ["derive"]}
