[package]
name = "rbfi"
version = "1.2.0"
edition = "2021"
description = "Extendable brainfuck interpreter written in Rust"
license = "BSD-3-Clause"
license-file = "LICENSE"
keywords = ["extendable","brainfuck","interpreter","wasm","cli"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
