on:
    push:
      branches:
        - develop
        - main
    workflow_dispatch:

name: build-pkg
jobs:
    build-package:
        name: Generate and Release binary 
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
          - uses: actions/checkout@v3
          - uses: cachix/install-nix-action@v12
          - name: Build Nix package
            run: nix --extra-experimental-features flakes --extra-experimental-features nix-command build .
          - name: Install github CLI
            run: |
              type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
              curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
              && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
              && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
              && sudo apt update \
              && sudo apt install gh -y
              tree .
              sha256sum ./result/rbfi > ./result/SHA256SUM